#!/bin/bash

DIR="db/migrations"
NAME_CREATE_MIGRATION=$2

CREATE_CMD="migrate create -ext sql -dir ${DIR} -seq ${NAME_CREATE_MIGRATION}"

RUN_MIGRATION_CMD="migrate -database ${WH_DBMIGRATION_URL} -path ${DIR} up"
RUN_DESTROY_CMD="migrate -database ${WH_DBMIGRATION_URL} -path ${DIR} down"

RUN_MIGRATION_TEST_CMD="migrate -database ${WH_DBMIGRATION_TEST_URL} -path ${DIR} up"
RUN_DESTROY_TEST_CMD="migrate -database ${WH_DBMIGRATION_TEST_URL} -path ${DIR} down"

if [ "$1" = "create" ]; then
  eval $CREATE_CMD
elif [ "$1" = "up" ]; then
  echo  "Creating tables"
  eval $RUN_MIGRATION_CMD
  echo  "Creating test tables"
  eval $RUN_MIGRATION_TEST_CMD
elif [ "$1" = "down" ]; then
  echo  "Deleting tables"
  eval $RUN_DESTROY_CMD
  echo  "Deleting test tables"
  eval $RUN_DESTROY_TEST_CMD
else
  echo "For create a migration run: ./migrator create [MIGRATION_NAME]"
  echo "For destroy migrations run: ./migrator down"
  echo "For execute migrations run: ./migrator up"
fi
